-- 회원 상태 테이블
DROP TABLE "MEMBER_STATUS";

CREATE TABLE "MEMBER_STATUS" (
	"STATUS_CD"	NUMBER	PRIMARY KEY,
	"STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_CD" IS '회원 상태 코드';

COMMENT ON COLUMN "MEMBER_STATUS"."STATUS_NM" IS '회원 상태 이름';


--회원 등급 테이블
DROP TABLE "MEMBER_GRADE";

CREATE TABLE "MEMBER_GRADE" (
	"GRADE_CD"	NUMBER	PRIMARY KEY,
	"GRADE_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "MEMBER_GRADE"."GRADE_CD" IS '회원 등급 코드';

COMMENT ON COLUMN "MEMBER_GRADE"."GRADE_NM" IS '회원 등급 이름';


--회원 테이블

DROP TABLE "MEMBER";

CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER	PRIMARY KEY,
	"MEMBER_ID"	VARCHAR2(20)		NOT NULL,
	"MEMBER_PW"	VARCHAR2(20)		NOT NULL,
	"MEMBER_NM"	VARCHAR2(15)		NOT NULL,
	"MEMBER_PHONE"	VARCHAR2(14)		NOT NULL,
	"MEMBER_EMAIL"	VARCHAR2(50)		NOT NULL,
	"MEMBER_ADDR"	VARCHAR2(200)		NULL,
	"ENROLL_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS_CD"	NUMBER	REFERENCES MEMBER_STATUS,
	"GRADE_CD"	NUMBER	REFERENCES MEMBER_GRADE
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS '회원아이디';

COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '비밀번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_NM" IS '회원명';

COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS '회원 휴대폰 번호';

COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';

COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';

COMMENT ON COLUMN "MEMBER"."STATUS_CD" IS '회원 상태 코드';

COMMENT ON COLUMN "MEMBER"."GRADE_CD" IS '회원등급코드';


-- 게시글 상태 테이블
DROP TABLE "BOARD_STATUS";

CREATE TABLE "BOARD_STATUS" (
	"BOARD_STATUS_CD"	NUMBER	PRIMARY KEY,
	"BOARD_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "BOARD_STATUS"."BOARD_STATUS_CD" IS '게시글 상태 코드';

COMMENT ON COLUMN "BOARD_STATUS"."BOARD_STATUS_NM" IS '게시글 상태 이름';


--카테고리
DROP TABLE "CATEGORY";

CREATE TABLE "CATEGORY" (
	"CATEGORY_CD"	NUMBER	PRIMARY KEY,
	"CATEGORY_NM"	VARCHAR2(50)		NOT NULL
);

COMMENT ON COLUMN "CATEGORY"."CATEGORY_CD" IS '카테고리 코드';

COMMENT ON COLUMN "CATEGORY"."CATEGORY_NM" IS '카테고리 명';


-- 게시판
DROP TABLE "BOARD";

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER	PRIMARY KEY,
	"BOARD_TITLE"	VARCHAR2(200)		NOT NULL,
	"BOARD_CONTENT"	CLOB		NOT NULL,
	"CREATE_DT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DT"	DATE	DEFAULT SYSDATE	NULL,
	"READ_COUNT"	NUMBER	DEFAULT 0	NOT NULL,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER,
	"BOARD_STATUS_CD"	NUMBER	REFERENCES BOARD_STATUS,
	"CATEGORY_CD"	NUMBER	REFERENCES CATEGORY
);

COMMENT ON COLUMN "BOARD"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "BOARD"."BOARD_TITLE" IS '게시글 제목';

COMMENT ON COLUMN "BOARD"."BOARD_CONTENT" IS '게시글 내용';

COMMENT ON COLUMN "BOARD"."CREATE_DT" IS '작성일';

COMMENT ON COLUMN "BOARD"."MODIFY_DT" IS '마지막 수정일';

COMMENT ON COLUMN "BOARD"."READ_COUNT" IS '조회수';

COMMENT ON COLUMN "BOARD"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "BOARD"."BOARD_STATUS_CD" IS '게시글 상태 코드';

COMMENT ON COLUMN "BOARD"."CATEGORY_CD" IS '카테고리 코드';


--댓글 상태 테이블
DROP TABLE "REPLY_STATUS";

CREATE TABLE "REPLY_STATUS" (
	"RELPY_STATUS_CD"	NUMBER	PRIMARY KEY,
	"REPLY_STATUS_NM"	VARCHAR2(20)		NOT NULL
);

COMMENT ON COLUMN "REPLY_STATUS"."RELPY_STATUS_CD" IS '댓글 상태 코드';

COMMENT ON COLUMN "REPLY_STATUS"."REPLY_STATUS_NM" IS '상태명';


-- 댓글 테이블
DROP TABLE "REPLY";

CREATE TABLE "REPLY" (
	"REPLY_NO"	NUMBER		NOT NULL,
	"REPLY_CONTENT"	VARCHAR2(1000)		NOT NULL,
	"REPLY_CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"BOARD_NO"	NUMBER	REFERENCES BOARD,
	"MEMBER_NO"	NUMBER	REFERENCES MEMBER,
	"REPLY_STATUS_CD"	NUMBER	REFERENCES REPLY_STATUS
);

COMMENT ON COLUMN "RLPLY"."REPLY_NO" IS '댓글 번호';

COMMENT ON COLUMN "RLPLY"."REPLY_CONTENT" IS '댓글 내용';

COMMENT ON COLUMN "RLPLY"."REPLY_CREATE_DATE" IS '댓글 작성일';

COMMENT ON COLUMN "RLPLY"."BOARD_NO" IS '게시글 번호';

COMMENT ON COLUMN "RLPLY"."MEMBER_NO" IS '회원번호';

COMMENT ON COLUMN "RLPLY"."REPLY_STATUS_CD" IS '댓글 상태 코드';

--시퀀스 생성 
CREATE SEQUENCE SEQ_MEMBER_NO; 
CREATE SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_REPLY_NO;


--------------------------------------------------------------------

-- sample data 

-- MEMBER _STATUS
INSERT INTO MEMBER_STATUS VALUES(100, '정상');
INSERT INTO MEMBER_STATUS VALUES(101, '탈퇴');
INSERT INTO MEMBER_STATUS VALUES(102, '정지');

commit;

--MEMBER_GRADE
INSERT INTO MEMBER_GRADE VALUES(200,'일반회원');
INSERT INTO MEMBER_GRADE VALUES(201,'관리자');

COMMIT;

--MEMBER 
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user01','pass01!','유저일','010-1234-1234', 
                          'user01@kh.or.kr','서울시 중구 남대문구 120 대일빌딩 2층 KH정보교육원', DEFAULT,100,200);
--MEMBER 
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL,'user02','pass02!','유저이','010-1234-1234', 
                          'user01@kh.or.kr','서울시 중구 남대문구 120 대일빌딩 2층 KH정보교육원', DEFAULT,102,200);
COMMIT;

-- MEMBER_PW 컬럼 크기 변경 (암호화한 비밀번호)
ALTER TABLE MEMBER MODIFY MEMBER_PW VARCHAR2(100);

--USER 01 PW CHANGE
UPDATE MEMBER SET
MEMBER_PW = 'aBN5hiegXlvAovJLipPoPd5LB+xjPrAeu1tcAVg0p5MKGocvo6l825SD+ZMCOcHBFeGB7MnzH31SAnDzYYsSdg=='
WHERE MEMBER_ID ='user01';

-- STATUS_CD 기본값
ALTER TABLE MEMBER MODIFY STATUS_CD DEFAULT 100;

ALTER TABLE MEMBER MODIFY GRADE_CD DEFAULT 200;

---------------------------------------------------------------


-- LOGIN SQL
SELECT MEMBER_NO, MEMBER_NM, MEMBER_PHONE,MEMBER_EMAIL,MEMBER_ADDR, ENROLL_DT, STATUS_CD, GRADE_CD
FROM MEMBER
WHERE MEMBER_ID = ? AND MEMBER_PW = ? ;


--SIGNUP 
IN

